export const START_POMODORO = 'START_POMODORO';
export const TOGGLE_PAUSE_POMODORO = 'TOGGLE_PAUSE_POMODORO';
export const DECREMENT_POMODORO_TIMER = 'DECREMENT_POMODORO_TIMER';
export const RESET_POMODORO = 'RESET_POMODORO';